parameters:

services:

    controller.pre_execute_listener:
        class: AppBundle\Listener\ControllerListener
        tags:
          -  { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    UploadService:
        class:     AppBundle\Service\UploadService
        arguments: [ "%kernel.root_dir%" ]

    PremiumService:
        class:     AppBundle\Service\PremiumService
        arguments: [ "@doctrine.orm.entity_manager" ]